import '../../../domain/entities/agent_mesh_entities.dart';
import '../../../domain/entities/noctros_enums.dart';
import '../agent.dart';
import '../agent_topics.dart';

/// Writes program artifacts after asking Architect and Inference for context.
class CoderAgent extends NoctrosAgent {
  @override
  AgentIdentity get identity => AgentIdentity.of(AgentRole.coder);

  @override
  Future<void> handle(AgentMessage message) async {
    if (message.topic != AgentTopics.designReady &&
        message.topic != AgentTopics.reviewChanges) {
      return;
    }

    await think(
      message.sessionId,
      message.topic == AgentTopics.reviewChanges
          ? 'Applying review notes to the program.'
          : 'Asking peers for contracts, then writing the program.',
    );

    final contract = await ask(
      sessionId: message.sessionId,
      to: AgentRole.architect,
      topic: AgentTopics.contractAsk,
      body: 'What public API should this program expose?',
    );

    final inference = await ask(
      sessionId: message.sessionId,
      to: AgentRole.inference,
      topic: AgentTopics.inferenceAsk,
      body: message.payload['goal'] as String? ?? message.body,
    );

    final goal = (message.payload['goal'] as String?) ??
        _goalFrom(message.body) ??
        'Hive program';
    final moduleName = (message.payload['moduleName'] as String?) ??
        _moduleNameFromContract(contract?.body) ??
        'HiveFeature';
    final fileName = (message.payload['fileName'] as String?) ??
        'lib/hive_generated/hive_feature.dart';
    final revised = message.topic == AgentTopics.reviewChanges;

    final source = _source(
      goal: goal,
      moduleName: moduleName,
      inferenceNote: inference?.body,
      revised: revised,
    );

    await publish(
      sessionId: message.sessionId,
      kind: AgentMessageKind.artifact,
      topic: AgentTopics.codeReady,
      to: AgentRole.reviewer,
      body: 'Program artifact ready at $fileName',
      payload: {
        'goal': goal,
        'moduleName': moduleName,
        'fileName': fileName,
        'artifact': source,
        'revised': revised,
      },
    );
  }

  String? _goalFrom(String body) {
    final match = RegExp(r'Architecture for: (.+)').firstMatch(body);
    return match?.group(1);
  }

  String? _moduleNameFromContract(String? contract) {
    if (contract == null) {
      return null;
    }
    final match = RegExp(r'class ([A-Za-z0-9]+)').firstMatch(contract);
    return match?.group(1);
  }

  String _source({
    required String goal,
    required String moduleName,
    required String? inferenceNote,
    required bool revised,
  }) {
    final safeGoal = _oneLine(goal);
    final docs = revised
        ? 'Revised after Hive review. $safeGoal'
        : 'Generated by the Noctros Hive Coder agent. $safeGoal';
    final extra = revised
        ? '''
  /// Reviewer-requested health check used by Automation.
  bool get isReady => true;
'''
        : '';
    final note = _oneLine(inferenceNote ?? 'none');
    final escapedGoal = safeGoal.replaceAll(r'\', r'\\').replaceAll("'", r"\'");

    return '''
/// $docs
/// Inference note: $note
class $moduleName {
  $moduleName({DateTime? clock}) : _createdAt = clock ?? DateTime.now().toUtc();

  final DateTime _createdAt;
  final List<String> _events = [];
$extra
  void execute({String note = 'run'}) {
    _events.add(note);
  }

  Map<String, Object?> snapshot() {
    return {
      'goal': '$escapedGoal',
      'createdAt': _createdAt.toIso8601String(),
      'events': List<String>.unmodifiable(_events),
      'hiveGenerated': true,
    };
  }
}
''';
  }

  String _oneLine(String value) => value.replaceAll('\n', ' ').trim();
}
